version: '3.4'

services:
  recruitmentsuitewebappapi:
    image: recruitmentsuitewebappapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4040:4040
